#!/bin/bash
./client_socket0
./client_socket1
./client_socket2
./client_socket1
./client_socket3
./client_socket1
./client_socket4
./client_socket1
./client_socket5
./client_socket1
./client_socket6
./client_socket1
./client_socket7
./client_socket1
./client_socket8
./client_socket1
./client_socket9
./client_socket1
./client_socket0
./client_socket1
./client_socket2
./client_socket1
./client_socket3
./client_socket1
./client_socket4
./client_socket1
./client_socket5
./client_socket1
./client_socket6
./client_socket1
./client_socket7
./client_socket1
./client_socket8
./client_socket1
./client_socket9
./client_socket1
./client_socket0
./client_socket1
./client_socket2
./client_socket1
./client_socket3
./client_socket1
./client_socket4
./client_socket1
./client_socket5
./client_socket1
./client_socket6
./client_socket1
./client_socket7
./client_socket1
./client_socket8
./client_socket1
./client_socket9
./client_socket1
./client_socket0
./client_socket1
./client_socket2
./client_socket1
./client_socket3
./client_socket1
./client_socket4
./client_socket1
./client_socket5
./client_socket1
./client_socket6
./client_socket1
./client_socket7
./client_socket1
./client_socket8
./client_socket1
./client_socket9
./client_socket1
